services:
  db:
    image: postgres:16.12
    container_name: conjuntos-postgres-local
    restart: unless-stopped
    environment:
      POSTGRES_DB: conjuntos
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
#    networks:
#      - conjuntos-network
#
#networks:
#  conjuntos-network:
#    driver: bridge
#
volumes:
  postgres_data:
    driver: local
