
# Actuator para healthchecks y monitoreo
management:
  endpoints:
    web:
      exposure:
        include: 'health,info,metrics,prometheus'
  endpoint:
    health:
      show-details: 'when-authorized'
  health:
    defaults:
      enabled: true

spring:
  profiles:
    active: default
  application:
    name: conjuntos
  datasource:
    url: 'jdbc:postgresql://localhost:5432/conjuntos'
    username: 'postgres'
    password: 'postgres'
    driver-class-name: 'org.postgresql.Driver'
  r2dbc:
    url: 'r2dbc:postgresql://localhost:5432/conjuntos'
    username: 'postgres'
    password: 'postgres'
    pool:
      initial-size: 5
      max-size: 10
      max-idle-time: '10m'
      validation-query: 'SELECT 1'

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: '/swagger-ui.html'
  api-docs:
    enabled: true
    path: '/v3/api-docs'

logging:
  level:
    root: 'INFO'
    com.william.conjuntos: 'DEBUG'
    org.springframework.r2dbc: 'DEBUG'
    io.r2dbc.postgresql.QUERY: 'DEBUG'
    org.springframework.security: 'DEBUG'
    org.springframework.boot.docker.compose: 'DEBUG'

